-- MySQL Script generated by MySQL Workbench
-- mar 17 nov 2020 21:11:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema regisprod
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema regisprod
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `regisprod` ;
USE `regisprod` ;

-- -----------------------------------------------------
-- Table `regisprod`.`tipo_identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`tipo_identificacion` (
  `idtipo_identificacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`idtipo_identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(30) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(60) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'activo',
  `tipo_identificacion_idtipo_identificacion` INT NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `tipo_identificacion_idtipo_identificacion`, `perfil_idperfil`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_identificacion_idx` (`tipo_identificacion_idtipo_identificacion` ASC) VISIBLE,
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_identificacion`
    FOREIGN KEY (`tipo_identificacion_idtipo_identificacion`)
    REFERENCES `regisprod`.`tipo_identificacion` (`idtipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `regisprod`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`modulo` (
  `idmodulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`idmodulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`permiso` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `perfil_idperfil` INT NOT NULL,
  `modulo_idmodulo` INT NOT NULL,
  PRIMARY KEY (`idpermiso`, `perfil_idperfil`, `modulo_idmodulo`),
  INDEX `fk_permiso_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  INDEX `fk_permiso_modulo1_idx` (`modulo_idmodulo` ASC) VISIBLE,
  CONSTRAINT `fk_permiso_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `regisprod`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_modulo1`
    FOREIGN KEY (`modulo_idmodulo`)
    REFERENCES `regisprod`.`modulo` (`idmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `correo` VARCHAR(50) NULL,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'activo',
  `tipo_identificacion_idtipo_identificacion` INT NOT NULL,
  PRIMARY KEY (`idproveedor`, `tipo_identificacion_idtipo_identificacion`),
  INDEX `fk_proveedor_tipo_identificacion1_idx` (`tipo_identificacion_idtipo_identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_tipo_identificacion1`
    FOREIGN KEY (`tipo_identificacion_idtipo_identificacion`)
    REFERENCES `regisprod`.`tipo_identificacion` (`idtipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` TEXT NULL,
  `costo` FLOAT NULL,
  `precio` FLOAT NOT NULL,
  `cant` INT NOT NULL DEFAULT 0,
  `estado` VARCHAR(30) NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `valor_total` FLOAT NULL,
  `proveedor_idproveedor` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idingreso`, `proveedor_idproveedor`, `usuario_idusuario`),
  INDEX `fk_ingreso_proveedor1_idx` (`proveedor_idproveedor` ASC) VISIBLE,
  INDEX `fk_ingreso_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_ingreso_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `regisprod`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `regisprod`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`producto_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`producto_ingreso` (
  `idproducto_ingreso` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `ingreso_idingreso` INT NOT NULL,
  PRIMARY KEY (`idproducto_ingreso`, `producto_idproducto`, `ingreso_idingreso`),
  INDEX `fk_producto_ingreso_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_producto_ingreso_ingreso1_idx` (`ingreso_idingreso` ASC) VISIBLE,
  CONSTRAINT `fk_producto_ingreso_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `regisprod`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_ingreso_ingreso1`
    FOREIGN KEY (`ingreso_idingreso`)
    REFERENCES `regisprod`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `valor_total` FLOAT NULL,
  `usuario_idusuario` INT NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`idventa`, `usuario_idusuario`, `cliente`),
  INDEX `fk_venta_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_venta_usuario2_idx` (`cliente` ASC) VISIBLE,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `regisprod`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario2`
    FOREIGN KEY (`cliente`)
    REFERENCES `regisprod`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regisprod`.`producto_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regisprod`.`producto_venta` (
  `idproducto_venta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `venta_idventa` INT NOT NULL,
  PRIMARY KEY (`idproducto_venta`, `producto_idproducto`, `venta_idventa`),
  INDEX `fk_producto_venta_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_producto_venta_venta1_idx` (`venta_idventa` ASC) VISIBLE,
  CONSTRAINT `fk_producto_venta_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `regisprod`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_venta_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `regisprod`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
